src/DevPodcasts.Web/Controllers/EpisodeController.cs
using DevPodcasts.ServiceLayer.Episode;
using DevPodcasts.Web.Features.Episode;
using DevPodcasts.Web.Features.Library;
using MediatR;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DevPodcasts.Web.Controllers
{
    public class EpisodeController : Controller
    {
        private readonly EpisodeService _episodeService;
        private readonly IMediator _mediator;

        public EpisodeController(IMediator mediator, EpisodeService episodeService)
        {
            _episodeService = episodeService;
            _mediator = mediator;
        }

        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Detail(int? id)
        {
            if (id == null ||  !_episodeService.EpisodeExists((int)id))
                return RedirectToAction("Index", "Home"); // TODO: redirect to error page

            var userId = User.Identity.GetUserId();
            var viewModel = await _mediator.Send(new Detail.Query {EpisodeId = (int)id, UserId = userId });

            return View(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> AddRemove(AddRemoveLibraryAjaxModel model)
        {
            var viewModel = await _mediator.Send(new AddOrRemoveEpisode.Command { UserId = model.U, EpisodeId = model.P });

            return Json(viewModel);
        }
    }
}

src/DevPodcasts.Web/Controllers/PodcastsController.cs
using DevPodcasts.Models;
using DevPodcasts.ServiceLayer.Podcast;
using DevPodcasts.ServiceLayer.Tag;
using DevPodcasts.ViewModels.Podcast;
using DevPodcasts.Web.Features.Library;
using DevPodcasts.Web.Features.Podcast;
using MediatR;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;

namespace DevPodcasts.Web.Controllers
{
    public class PodcastsController : Controller
    {
        private readonly PodcastService _podcastService;
        private readonly TagService _tagService;
        private readonly IMediator _mediator;

        public PodcastsController(
            PodcastService podcastService, 
            TagService tagService,
            IMediator mediator)
        {
            _tagService = tagService;
            _podcastService = podcastService;
            _mediator = mediator;
        }

        public ActionResult Index(int? page)
        {
            var viewModel = _podcastService.Search();

            return View(viewModel);
        }

        public ActionResult Tagged(string tagSlug)
        {
            if (!string.IsNullOrEmpty(tagSlug))
            {
                var viewModel = _tagService.GetTaggedPodcasts(tagSlug);
                return View(viewModel);
            }
            return View();
        }

        [Authorize]
        public ActionResult Submit()
        {
            return View(new SubmitForReview.Model());
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Submit(SubmitPodcastViewModel model)
        {
            var command = Mapper.Map<SubmitPodcastViewModel, SubmitForReview.Command>(model);
            var result = await _mediator.Send(command);
            return View(result);
        }

        public async Task<ActionResult> Detail(int? id)
        {
            if (id == null || !_podcastService.PodcastExists((int)id))
                return RedirectToAction("Index", "Home"); // TODO: redirect to error page

            var userId = User.Identity.GetUserId();
            var viewModel = await _mediator.Send(new Detail.Query { PodcastId = (int)id, UserId = userId });

            return View(viewModel);
        }

        private bool IsInteger(object value)
        {
            return false;
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var viewModel = _podcastService.Edit(id);
            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(EditPodcastViewModel model)
        {
            await _podcastService.UpdatePodcast(model);
            return RedirectToAction("ManagePodcasts", "Admin");
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int Id)
        {
            await _podcastService.DeletePodcast(Id);

            return RedirectToAction("ManagePodcasts", "Admin");
        }

        [HttpPost]
        public async Task<ActionResult> AddRemove(AddRemoveLibraryAjaxModel model)
        {
            var viewModel = await _mediator.Send(new AddOrRemovePodcast.Command { UserId = model.U, PodcastId = model.P } );

            return Json(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> SubscribeUnsubscribeEmail(AddRemoveLibraryAjaxModel model)
        {
            var viewModel = await _mediator.Send(new SubscribeUnsubscribeEmailNotification.Command { UserId = model.U, PodcastId = model.P });

            return Json(viewModel);
        }
    }
}

src/DevPodcasts.Web/Views/Podcasts/Detail.cshtml
@using DevPodcasts.Web.Extensions
@model DevPodcasts.ViewModels.Podcast.PodcastDetailViewModel
@{
    ViewBag.Title = Model.Title;
    ViewBag.MetaDescriptionText = Model.Description;
    var isSubscribed = Model.IsSubscribed;
}

<div class="podcast-detail-container">
    <div class="header-row">
        <div class="col-sm-10">
            <h2>@Model.Title</h2>
            <p><a href="@Model.SiteUrl" rel="noopener noreferrer" target="_blank">@Model.SiteUrl</a></p>
            <p>@Html.Raw(@Model.Description)</p>
            <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
            <span class="tag-text"><strong>Tags: </strong></span>
            <div class="podcast-tags">
                @if (Model.Tags != null)
                {
                    foreach (var tag in Model.Tags)
                    {
                        <a href="~/tags/@tag.Slug" class="podcast-tag" title="Podcasts tagged @tag.Name">@tag.Name</a>
                    }
                }
            </div>
        </div>
        <div class="col-sm-2">
            <img class="podcast-img" src="@Model.ImageUrl" />
        </div>
    </div>
    <div class="button-row">
        @if (User.Identity.IsAuthenticated)
        {
            <button class="btn btn-primary add-remove" id="remove-from-libary" title="Remove from Library" @(isSubscribed ? "style=display:inline-block" : "style=display:none")><span class="glyphicon glyphicon-ok"></span>Added</button>
            <button class="btn btn-primary add-remove" id="add-to-libary" title="Add to Library" @(isSubscribed ? "style=display:none" : "style=display:inline-block")><span class="glyphicon glyphicon-plus"></span>Add</button>
        }
        else
        {
            <a href='@Url.Action("Login", "Account", new { ReturnUrl = "~/podcasts/detail/" + Model.Id })'><button class="btn btn-primary" title="Sign in to add podcast to Library"><span class="glyphicon glyphicon-plus"></span>Add</button></a>
        }
        <input type="text" id="search-episodes" onkeyup="search()" class="form-control" placeholder="Search episodes...">
    </div>

    <table class="table table-striped" id="podcast-episodes">
        <thead>
            <tr>
                <th>Title</th>
                <th>Date Published</th>
            </tr>
        </thead>
        <tbody>
            @if (Model?.Episodes != null)
            {
                foreach (var item in Model.Episodes)
                {
                    <tr>
                        <td>@Html.ActionLink(item.Title, "Detail", "Episode", new { id = item.Id }, null)</td>
                        <td>@item.DatePublished.ToShortUkDate()</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function() {
        $('.add-remove').on('click',
            function() {

                var data = {
                    u: '@Model.UserId',
                    p: '@Model.Id'
                }

                $.ajax({
                    url: "/Podcasts/AddRemove",
                    type: "POST",
                    data: JSON.stringify(data),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function(response) {
                        console.log(response.IsSuccess);
                        if (response.IsAdded) {
                            $('#add-to-libary').hide();
                            $('#remove-from-libary').show();
                        } else {
                            $('#remove-from-libary').hide();
                            $('#add-to-libary').show();
                        }
                    }
                });
            })

        $('#remove-from-libary').mouseover(function() {
            // change text to remove
        });

        
    });

    function search() {
        // Declare variables 
        var input, filter, table, tr, td, i;
        input = document.getElementById("search-episodes");
        filter = input.value.toUpperCase();
        table = document.getElementById("podcast-episodes");
        tr = table.getElementsByTagName("tr");

        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            } 
        }
    }

</script>

src/DevPodcasts.Web/Views/Podcasts/Edit.cshtml
@model DevPodcasts.ViewModels.Podcast.EditPodcastViewModel
@{
    ViewBag.Title = "Edit";
}

<div class="edit-podcast-container">
    <h2>Edit Podcast</h2>

    @using (Html.BeginForm("Edit", "Podcasts", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.Title)
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Description)
            @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ImageUrl)
            @Html.TextBoxFor(m => m.ImageUrl, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.FeedUrl)
            @Html.TextBoxFor(m => m.FeedUrl, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.SiteUrl)
            @Html.TextBoxFor(m => m.SiteUrl, new { @class = "form-control" })
        </div>
        <div>
            <h4>Tags</h4>
        </div>
        <div>
            @Html.EditorFor(m => m.Tags)
        </div>
        <input type="submit" value="Save" class="btn btn-primary" />
    }

    <hr/>

    @using (Html.BeginForm("Delete", "Podcasts", FormMethod.Post, new { onsubmit = "return confirm('Are you sure?');" }))
    {
        @Html.HiddenFor(p => p.Id);

        <input type="submit" value="Delete Podcast" class="btn btn-danger" id="delete-podcast" />
    }

</div>

src/DevPodcasts.Web/Views/Podcasts/Index.cshtml
@model DevPodcasts.ViewModels.Podcast.PodcastIndexViewModel
@{
    ViewBag.Title = "Podcasts";
    var episodeCount = Model.EpisodeCount;
}

<div class="podcasts-container">
    
    <h2>Podcasts</h2>

    <div style="margin: 25px 0;">
        @if (Model == null)
        {
            <h4>0 podcasts</h4>
        }
        else if (Model.Items.Count() == 1)
        {
            <h4>1 podcast</h4>
        }
        else
        {
            <h4>@Model.Items.Count() podcasts</h4>
        }
        <h4>@episodeCount episodes</h4>
    </div>

    @Html.Partial("_PodcastRows", Model.Items)

</div>

src/DevPodcasts.Web/Views/Podcasts/Submit.cshtml
@using DevPodcasts.Models
@model DevPodcasts.Web.Features.Podcast.SubmitForReview.Model
@{
    ViewBag.Title = "Submit a podcast";
    var successResult = Model.SuccessResult;
}

<h2>Submit a podcast</h2>


@using (Html.BeginForm("Submit", "Podcasts", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Enter podcast RSS feed URL.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.RssFeedUrl, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.RssFeedUrl, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Submit" />
        </div>
    </div>
}

@if (successResult == SuccessResult.InvalidUrl)
{
    <div id="alert" class="alert alert-danger">
        <h4>Invalid URL, please try again.</h4>
    </div>
}
else if (successResult == SuccessResult.AlreadyExists)
{
    <div id="alert" class="alert alert-warning">
        <h4>Podcast already exists in the database</h4>
    </div>
}
else if (successResult == SuccessResult.Error)
{
    <div id="alert" class="alert alert-danger">
        <h4>An error occurred, please try again.</h4>
    </div>
}
else if (successResult == SuccessResult.Success)
{
    <div id="alert" class="alert alert-success">
        <h4>Thank you for submitting, we will email you once the podcast has been reviewed by admin.</h4>
    </div>
}
else
{
    <div id="alert">
        
    </div>
}

<script>
    $('#alert').delay(4000).fadeOut('slow');
</script>

src/DevPodcasts.Web/Views/Podcasts/Tagged.cshtml
@model DevPodcasts.ViewModels.Tags.TagResultViewModel
@{
    ViewBag.Title = Model.TagName;
}

<div class="tag-results-container">
    <h2>Podcasts tagged <span style="color: rgba(4, 59, 127, 0.95); margin-left: 5px">@Model.TagName</span></h2>

    @Html.Partial("_PodcastRows", Model.SearchResults)

</div>

<script>
    $(document).ready(function () {
        $(".result-row").click(function () {
            var id = this.id;
            document.location.href = getURL() + "podcasts/detail/" + id;
        })
    });

    function getURL() {
        var arr = window.location.href.split("/");
        delete arr[arr.length - 1];
        var url = arr.join("/").replace("podcasts/tagged/", "");
        return url;
    }
</script>