src/DevPodcasts.Web/Controllers/LogsController.cs
using DevPodcasts.ServiceLayer.Logging;
using System.Web.Mvc;

namespace DevPodcasts.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LogsController : Controller
    {
        private readonly LogService _logService;
        private const int ItemsPerPage = 50;

        public LogsController(LogService logService)
        {
            _logService = logService;
        }

        public ActionResult Index(int? page, string filter)
        {
            if (filter == "Select a level")
                filter = null;

            var viewModel = _logService.GetIndexViewModel(page ?? 0, ItemsPerPage, filter);
            ViewBag.Filter = filter;
            
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Query(int? page, string filter)
        {
            if (filter == "Select a level")
                filter = null;

            var logs = _logService.GetLogs(page ?? 0, ItemsPerPage, filter);
            ViewBag.Filter = filter;

            return Json(new { filter = filter, html = PartialView("_LogResultsTable", logs) });
        }
    }
}

src/DevPodcasts.Web/Views/Shared/_Footer.cshtml
<footer id="footer">
    <div class="container">
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="column">
                <h4>Site Map</h4>
                <div class="footer-2-col col-lg-6 col-md-6 col-sm-6">
                    <ul>
                        <li>@Html.ActionLink("Home", "Index", "Home", null, new { @class = "footer-a" })</li>
                        <li>@Html.ActionLink("Podcasts", "Index", "Podcasts", null, new { @class = "footer-a" })</li>
                        <li>@Html.ActionLink("Tags", "Index", "Tags", null, new { @class = "footer-a" })</li>
                        <li>@Html.ActionLink("Library", "Index", "Library", null, new { @class = "footer-a" })</li>
                        <li>@Html.ActionLink("Search", "Index", "Search", null, new { @class = "footer-a" })</li>
                    </ul>
                </div>
                <div class="footer-2-col col-lg-6 col-md-6 col-sm-6">
                    <ul>
                        <li>@Html.ActionLink("Submit a podcast", "Submit", "Podcasts", null, new { @class = "footer-a" })</li>
                        <li>@Html.ActionLink("Login", "Login", "Account", null, new { @class = "footer-a" })</li>
                        <li>@Html.ActionLink("Register", "Register", "Account", null, new { @class = "footer-a"} )</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="column">
                <h4>Contact</h4>
                <ul>
                    <li>@Html.ActionLink("Contact form", "Contact", "Home", null, new { @class = "footer-a", title = "Report an issue or a bug, request a feature" })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="nrkirby">
        Created by <a href="https://nrkirby.co.uk">NRKirby</a>
    </div>
</footer>

src/DevPodcasts.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@{
    string searchQuery = ViewBag.SearchQuery;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Global Site Tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-63521630-3"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments) };
        gtag('js', new Date());

        gtag('config', 'UA-63521630-3');
    </script>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @if (string.IsNullOrEmpty(ViewBag.MetaDescriptionText))
    {
        <meta name="description" content="A directory of podcasts for software developers - we list over 100 podcasts and over 17,000 episodes of interest to all kinds of software developers and engineers.">
    }
    else
    {
        <meta name="description" content="@ViewBag.MetaDescriptionText">
    }

    <meta name="keywords" content="software developer podcasts, software development podcasts, software engineering podcasts, javascript podcasts, python podcasts, java podcasts, .net podcasts, c++ podcasts, angular podcasts, dev podcasts, developer podcasts, software podcasts">
    <title>@ViewBag.Title | Dev Podcasts</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="shortcut icon" href="~/favicon.png" type="image/png">
    <link rel="icon" href="~/favicon.png" type="image/png">
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <meta name="yandex-verification" content="daf29dc516a8a4d7" />

    @if (IsSectionDefined("AddToHead"))
    {
        @RenderSection("AddToHead", required: false)
    }
</head>
<body>
    <nav id="topbar" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Dev Podcasts", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", title = "Home page" })
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/podcasts">Podcasts</a></li>
                    <li><a href="/tags">Tags</a></li>
                    <li><a href="/library">Library</a></li>
                    @if (ViewContext.HttpContext.User.IsInRole("Admin"))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Manage submissions", "Index", "Admin")</li>
                                <li>@Html.ActionLink("Manage podcasts", "ManagePodcasts", "Admin")</li>
                                <li>@Html.ActionLink("View Logs", "Index", "Logs")</li>
                            </ul>
                        </li>
                    }
                </ul>
                <div class="nav navbar-nav navbar-right">
                    @using (Html.BeginForm("Index", "Search", FormMethod.Get, new { @class = "navbar-form" }))
                    {
                        <div class="input-group">
                            @if (searchQuery != null)
                            {
                                <input type="text" class="form-control search-box" placeholder="Search podcasts..." name="q" value=@searchQuery>
                            }
                            else
                            {
                                <input type="text" class="form-control search-box" placeholder="Search podcasts..." name="q">
                            }
                            <div class="input-group-btn">
                                <button class="btn btn-default search-btn" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    }
                </div>
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()

                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@User.Identity.GetUserName() <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>
                                        @Html.ActionLink("Account settings", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                                    </li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                                </ul>
                            </li>
                        </ul>
                    }
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                        <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                    </ul>
                }
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Html.Partial("_Footer")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

src/DevPodcasts.Web/Views/Shared/_PodcastRows.cshtml
@model IEnumerable<DevPodcasts.ViewModels.Podcast.PodcastSearchResultViewModel>


<div id="results-container">
    @if (Model != null)
    {
        <hr />
        foreach (var result in Model)
        {
            <div class="row result-row" id="@result.Id" title="@result.Title">
                <div class="col-sm-2 hidden-xs">
                    <a href="~/podcasts/detail/@result.Id"><img class="result-img" src="@result.ImageUrl" alt="@result.Title logo"/></a>
                </div>
                <div class="col-sm-10">
                    <a href="~/podcasts/detail/@result.Id"><h3>@result.Title</h3></a>
                    <p>@result.Description</p>
                    <div class="row">
                        <div class="podcast-tag-list col-sm-10">
                            <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
                            <span class="tag-text"><strong>Tags: </strong></span>
                            <div class="podcast-tags">
                                @if (result.Tags != null)
                                {
                                    foreach (var tag in result.Tags)
                                    {
                                        <a href="~/tags/@tag.Slug" class="podcast-tag" title="Podcasts tagged @tag.Name">@tag.Name</a>
                                    }
                                }
                            </div>
                        </div>
                        <div class="col-sm-2"><p class="pull-right"><a href="~/podcasts/detail/@result.Id"><span class="result-episode-count">@result.NumberOfEpisodes episodes</span></a></p></div>
                    </div>
                </div>
            </div>
            <hr />
        }
    }
</div>