DevPodcasts.Web/Models/IdentityModels.cs
using System.Data.Entity;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace DevPodcasts.Web.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("DefaultConnection", throwIfV1Schema: false)
        {
        }

        public static ApplicationDbContext Create()
        {
            return new ApplicationDbContext();
        }
    }
}

DevPodcasts.Web/Controllers/PodcastController.cs
using DevPodcasts.ServiceLayer.Podcast;
using DevPodcasts.ViewModels.Podcast;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DevPodcasts.Web.Controllers
{
    public class PodcastController : Controller
    {
        private readonly PodcastService _podcastService;

        public PodcastController(PodcastService podcastService)
        {
            _podcastService = podcastService;
        }

        public ActionResult Index()
        {
            var viewModel = _podcastService.Search();
            return View(viewModel);
        }

        [Authorize]
        public ActionResult Submit()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Submit(SubmitPodcastViewModel model)
        {
            var result = await _podcastService.SubmitPodcastForReview(model);
            return View(result);
        }

        public ActionResult Detail(int id)
        {
            var podcastExists = _podcastService.PodcastExists(id);
            if (!podcastExists)
                return RedirectToAction("Index", "Home"); // TODO: redirect to error page

            var viewModel = _podcastService.GetPodcastDetail(id);
            return View(viewModel);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var viewModel = _podcastService.Edit(id);
            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(EditPodcastViewModel model)
        {
            await _podcastService.UpdatePodcast(model);
            return RedirectToAction("ManagePodcasts", "Admin");
        }
    }
}

DevPodcasts.Web/Controllers/TagController.cs
using System.Web.Mvc;
using DevPodcasts.ServiceLayer.Tag;

namespace DevPodcasts.Web.Controllers
{
    public class TagController : Controller
    {
        private readonly TagService _tagService;

        public TagController(TagService tagService)
        {
            _tagService = tagService;
        }

        public ActionResult Index(string tagSlug)
        {
            var viewModel = _tagService.GetTags();

            return View(viewModel);
        }
    }
}

DevPodcasts.Web/Views/Podcast/Add.cshtml
@model DevPodcasts.ViewModels.Podcast.AddPodcastViewModel
@{
    ViewBag.Title = "AddPodcastForReview";
}

<h2>AddPodcastForReview Podcast</h2>


@using (Html.BeginForm("Add", "Podcast", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Enter podcast RSS feed URL.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.RssFeedUrl, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.RssFeedUrl, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="AddPodcastForReview" />
        </div>
    </div>
}

DevPodcasts.Web/Views/Podcast/Edit.cshtml
@model DevPodcasts.ViewModels.Podcast.EditPodcastViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit Podcast</h2>

@using (Html.BeginForm("Edit", "Podcast", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Title)
        @Html.TextBoxFor(m => m.Title, new {@class = "form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Description)
        @Html.TextBoxFor(m => m.Description, new {@class = "form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ImageUrl)
        @Html.TextBoxFor(m => m.ImageUrl, new {@class = "form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.FeedUrl)
        @Html.TextBoxFor(m => m.FeedUrl, new {@class = "form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.SiteUrl)
        @Html.TextBoxFor(m => m.SiteUrl, new {@class = "form-control"})
    </div>
    <div>
        <h4>Tags</h4>
    </div>
    <div>
        @Html.EditorFor(m => m.Tags)
    </div>
    <input type="submit" value="Save" />
}

DevPodcasts.Web/Views/Podcast/Index.cshtml
@model DevPodcasts.ViewModels.Podcast.PodcastIndexViewModel
@{
    ViewBag.Title = "Podcasts";
    var episodeCount = Model.EpisodeCount;
}

<h2 style="position: relative; top: 20px">Podcasts</h2>

<div style="position: relative; top: 25px">
    @if (Model == null)
    {
        <h4>0 podcasts</h4>
    }
    else if (Model.Items.Count() == 1)
    {
        <h4>1 podcast</h4>
    }
    else
    {
        <h4>@Model.Items.Count() podcasts</h4>
    }
    <h4>@episodeCount episodes</h4>
</div>
<div style="position: relative; top: 50px; border-top: 1px solid #e4e6e8; margin-bottom: 75px">
    <ul id="search-list">
        @if (Model != null)
        {
            foreach (var result in Model.Items)
            {
                <li class="podcast-list-item">
                    <div class="search-result">
                        <div class="podcast-image">
                            <a href='@Url.Action("Detail", "Podcast", new {id = result.Id})'>
                                <img class="img-thumb" src="@result.ImageUrl" />
                            </a>
                        </div>
                        <div class="podcast-summary">
                            <p>
                                @Html.ActionLink(result.Title, "Detail", "Podcast", new { id = result.Id }, null) 
                            </p>
                            <p>@result.Description</p>
                        </div>
                        <p class="episode-count pull-right" align="right">
                            <strong>(@result.NumberOfEpisodes episodes)</strong>
                        </p>
                        
                    </div>
                </li>
            }
        }
    </ul>
</div>

DevPodcasts.Web/Views/Podcast/Submit.cshtml
@model DevPodcasts.ViewModels.Podcast.SubmitPodcastViewModel
@{
    ViewBag.Title = "Submit a podcast";
}

<h2>Submit a podcast</h2>


@using (Html.BeginForm("Submit", "Podcast", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Enter podcast RSS feed URL.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.RssFeedUrl, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.RssFeedUrl, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Submit" />
        </div>
    </div>
}